//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompoundProduct
    {
        public CompoundProduct()
        {
            this.CompoundProductComboes = new HashSet<CompoundProductCombo>();
            this.CompoundProductFoodInputs = new HashSet<CompoundProductFoodInput>();
        }
    
        public int Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<CompoundProductCombo> CompoundProductComboes { get; set; }
        public virtual ICollection<CompoundProductFoodInput> CompoundProductFoodInputs { get; set; }
    }
}
