//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompoundProductFoodInput
    {
        public int CompoundProductId { get; set; }
        public int FoodInputId { get; set; }
        public int RequiredUnits { get; set; }
    
        public virtual CompoundProduct CompoundProduct { get; set; }
        public virtual FoodInput FoodInput { get; set; }
    }
}
