//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    using System.Linq;

    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CashMovement> CashMovements { get; set; }
        public virtual DbSet<CategoryType> CategoryTypes { get; set; }
        public virtual DbSet<Combo> Comboes { get; set; }
        public virtual DbSet<CompoundProduct> CompoundProducts { get; set; }
        public virtual DbSet<CompoundProductCombo> CompoundProductComboes { get; set; }
        public virtual DbSet<CompoundProductFoodInput> CompoundProductFoodInputs { get; set; }
        public virtual DbSet<FoodInput> FoodInputs { get; set; }
        public virtual DbSet<FoodInputCombo> FoodInputComboes { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SaleDetail> SaleDetails { get; set; }
        public virtual DbSet<SaleType> SaleTypes { get; set; }
        public virtual DbSet<SimpleProduct> SimpleProducts { get; set; }
        public virtual DbSet<SimpleProductCombo> SimpleProductComboes { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ProductView> ProductViews { get; set; }

        public decimal GetProductCost(int productId)
        {
            return this.Database.SqlQuery<decimal>(
                "SELECT dbo.GetProductCost(@someParameter)",
                new SqlParameter("someParameter", productId)
                ).First();
        }

        public int GetProductUnits(int productId)
        {
            return this.Database.SqlQuery<int>(
                "SELECT dbo.GetProductUnits(@someParameter)",
                new SqlParameter("someParameter", productId)
                ).First();
        }

        public string GetProductType(int productId)
        {
            return this.Database.SqlQuery<string>(
                "SELECT dbo.GetProductType(@someParameter)",
                new SqlParameter("someParameter", productId)
                ).First();
        }
    }
}
