//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BillConfig> BillConfigs { get; set; }
        public DbSet<CashMovement> CashMovements { get; set; }
        public DbSet<CategoryType> CategoryTypes { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Combo> Comboes { get; set; }
        public DbSet<CompoundProduct> CompoundProducts { get; set; }
        public DbSet<CompoundProductCombo> CompoundProductComboes { get; set; }
        public DbSet<CompoundProductFoodInput> CompoundProductFoodInputs { get; set; }
        public DbSet<FoodInput> FoodInputs { get; set; }
        public DbSet<FoodInputCombo> FoodInputComboes { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<OrderState> OrderStates { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Provider> Providers { get; set; }
        public DbSet<Purchase> Purchases { get; set; }
        public DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<SaleDetail> SaleDetails { get; set; }
        public DbSet<SaleOrder> SaleOrders { get; set; }
        public DbSet<SaleOrderDetail> SaleOrderDetails { get; set; }
        public DbSet<SaleType> SaleTypes { get; set; }
        public DbSet<SimpleProduct> SimpleProducts { get; set; }
        public DbSet<SimpleProductCombo> SimpleProductComboes { get; set; }
        public DbSet<UnitType> UnitTypes { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
