//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodInput
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodInput()
        {
            this.CompoundProductFoodInputs = new HashSet<CompoundProductFoodInput>();
            this.FoodInputComboes = new HashSet<FoodInputCombo>();
        }
    
        public int Id { get; set; }
        public int UnitTypeId { get; set; }
        public int UnitValue { get; set; }
        public decimal UnitCost { get; set; }
        public int Units { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompoundProductFoodInput> CompoundProductFoodInputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodInputCombo> FoodInputComboes { get; set; }
        public virtual Product Product { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
