//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long Id { get; set; }
        public long SaleId { get; set; }
        public int DailyId { get; set; }
        public string OrderName { get; set; }
        public string Observation { get; set; }
        public bool Committed { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
