//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public int Id { get; set; }
        public string ProductType { get; set; }
        public int CategoryTypeId { get; set; }
        public string CategoryDescription { get; set; }
        public string Description { get; set; }
        public decimal UnitSaleValue { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<int> AvailableUnits { get; set; }
        public decimal SaleDiscount { get; set; }
    }
}
