//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        public SaleOrder()
        {
            this.SaleOrderDetails = new HashSet<SaleOrderDetail>();
        }
    
        public long Id { get; set; }
        public long LoginId { get; set; }
        public long OrderStateId { get; set; }
        public string OrderName { get; set; }
        public string Observation { get; set; }
        public string PhoneNumber { get; set; }
        public int DailyId { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool Hide { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual ICollection<SaleOrderDetail> SaleOrderDetails { get; set; }
    }
}
