//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
        }
    
        public long Id { get; set; }
        public long LoginId { get; set; }
        public int SaleTypeId { get; set; }
        public int ClientId { get; set; }
        public int DailyId { get; set; }
        public int BillNumber { get; set; }
        public string ControlCode { get; set; }
        public System.DateTime DateTime { get; set; }
        public bool Hide { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Login Login { get; set; }
        public virtual SaleType SaleType { get; set; }
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
    }
}
