//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleProduct
    {
        public SimpleProduct()
        {
            this.SimpleProductComboes = new HashSet<SimpleProductCombo>();
        }
    
        public int Id { get; set; }
        public int Units { get; set; }
        public decimal UnitCost { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<SimpleProductCombo> SimpleProductComboes { get; set; }
    }
}
